### ISSUE TITLE
[Update] Vue axios 관련 포스팅

### ISSUE THREAD

**Issue by myungseokang** [vuejs-kr/vuejs-kr.github.io#105]
https://vuejs-kr.github.io/update/2017/01/04/http-request-with-axios/

위의 포스팅에서 v-for 디렉티브를 사용하는데, [key 가 바인딩 되지 않아서 렌더링이 되지 않는 문제](https://kr.vuejs.org/v2/guide/list.html#컴포넌트와-v-for) 가 있습니다.
예전 포스팅이긴하나 axios 관련된 한국어 자료가 많이 없는 걸로 미루어보아 업데이트를 해놓으면 좋을 것 같다는 생각이 들어 이슈남깁니다.
항상 포스팅 잘 보고 있습니다.
감사합니다.

**Comment by ChangJoo-Park** [comment]
감사합니다 👍
