### ISSUE TITLE
vuex 한글 페이지 404 에러 나고 있습니다

### ISSUE THREAD

**Issue by usolkim** [vuejs-kr/vuejs-kr.github.io#113]
(최소) 지난주 금요일부터 vuex 한글 페이지 접속시 404 에러 화면이 나오고 있습니다.
(제가 확인한 것이 지난주 금요일인 것이고, 그 이전부터 발생했을 수도 있습니다)
잠시 작업중인가 싶어서 기다려봤는데 현재까지도 동일한 에러가 발생하고 있네요.
공홈에서도 "Languages"를 클릭하면 한국어 가 노출되지 않고 있습니다.
무슨 일이 있었나요??

추신. vuex repo 에서는 issue 탭이 없어서 여기에 등록했습니다.

**Comment by usolkim** [comment]
혹시나 다른 링크들도 확인해봤는데.. vue-router 와 vue-ssr 도 404 에러가 발생하네요.
https://router.vuejs.org/kr/
https://ssr.vuejs.org/ko/

**Comment by ChangJoo-Park** [comment]
감사합니다 ㅠ_ㅠ

**Comment by ChangJoo-Park** [comment]
vuepress 로 다 변경했나보네요

**Comment by usolkim** [comment]
그러네요.. 6일전에 vuepress 로 바꿨네요;;
신기(?)한게 일본은 어떻게 바로 알고 대응을 한걸까요?;;

**Comment by ChangJoo-Park** [comment]
아마 이슈가 어디 있을텐데 제가 잘 안봐서 그런가봅니다 😭

**Comment by usolkim** [comment]
음 예고도 없이 그냥 작업한 것 같네요;
아무리 찾아봐도 공지나 예고가 없네요.
관련 이슈도 딱히 안 보이구요.. (PR 한 분이 올린 이슈 밖에는..)
꽤 많은 언어로 번역되어 있었는데.. 한 순간에 다 사라졌네요;; (물론 백업은 해놨다지만..)
오픈소스 진영에서는 이런 일이 다반사인가요?
이런 사태가 살짝 당황스럽네요..
제가 아직 적응이 안 된걸까요;;

**Comment by usolkim** [comment]
@ChangJoo-Park 제가 vuepress 로 변환 작업 해도 될까요?

**Comment by usolkim** [comment]
@ChangJoo-Park 
https://github.com/usolkim/vuex
fork 해서 변환 작업 해봤습니다.
한번 검토해주시고 문제 없다면 PR 하겠습니다.
혹시나 제가 하면 안 되면 부담없이 얘기해주세요~

**Comment by ChangJoo-Park** [comment]
감사합니다 :) 저녁에 확인하고 말씀드리겠습니다 (_ _)

**Comment by usolkim** [comment]
@ChangJoo-Park 
vuepress 기반으로 변환 작업만 하면 될 줄 알았는데요..
다시 살펴보니.. 내용도 일부 바뀐 부분이 있네요..
일단 api reference 내용만 현행화? 해놨습니다.
확인 부탁드립니다.

**Comment by ChangJoo-Park** [comment]
감사합니다 제가 router 부터 확인해볼 예정인데 진행을 어떻게 할 지 고민해볼게요

**Comment by ChangJoo-Park** [comment]
@usolkim 
저는 그냥 PR했어요 나중에 리뷰어 알려달라고 하면 @usolkim 님을 리뷰어로 해달라고 해도 괜찮을까요?

https://github.com/vuejs/vue-router/pull/2228

**Comment by usolkim** [comment]
@ChangJoo-Park 
네^^ 저야 감사하죠 ㅎㅎ

**Comment by ChangJoo-Park** [comment]
@usolkim 어제 Vuex작업해주신거 보고 피드백을 드린줄 알았어요

지금 작업 하신거 Vuex 공식 저장소에 PR 해주실 수 있나요? 제가 리뷰 했다고 써주시면 됩니다

**Comment by usolkim** [comment]
@ChangJoo-Park PR 했습니다^^

**Comment by usolkim** [comment]
@ChangJoo-Park vue-router 의 api reference 에서 일부 링크들이 오동작하고 있네요.
vuepress 로 전환하면서 api 와 guide 폴더가 나뉘면서 상대경로가 바뀌어서 그래요.
하나 예시로 말씀드리면..
/api/#router-aftereach 에서 네비게이션 가드 부분 링크가 
../advanced/navigation-guards.md
에서
../guide/advanced/navigation-guards.md
로 guide 폴더가 추가되어야 합니다 ^^

**Comment by ChangJoo-Park** [comment]
허.. 제가 눌러본다고 눌러봤는데 놓친게 많네요
저녁에 작업하겠습니다 ;ㅂ;

확인해주셔서 감사합니다 👍 

---
아바타 바꾸셨네요 ㅋㅋ

**Comment by usolkim** [comment]
기본 이미지가 너무 허전?해서 바꿔봤습니다 ㅎㅎ

**Comment by ChangJoo-Park** [comment]
vue-router 문서 업데이트 했습니다 :)

**Comment by usolkim** [comment]
아직 일부 링크 오류가 있어서 수정 후 [PR](https://github.com/ChangJoo-Park/vue-router/pull/1) 했습니다
확인 부탁드립니다

API 레퍼런스에 새로 추가된 내용으로 링크가 걸려있네요.. 일단 에러는 안 나게 링크만 걸어놨습니다.

**Comment by ChangJoo-Park** [comment]
감사합니다 ㅠㅠ

**Comment by usolkim** [comment]
고생하셨습니다.
아직 머지는 안됐지만 일단 PR 해놨으니 이슈 닫겠습니다^^
