### ISSUE TITLE
vuex 한글화 작업 리뷰 요청드립니다

### ISSUE THREAD

**Issue by usolkim** [vuejs-kr/vuejs-kr.github.io#115]
@ChangJoo-Park 
Vuex 한글화 안 된 부분에 대해서 작업 완료하였습니다.
리뷰 부탁 드립니다.
(리뷰는 보통 어떻게 요청하나요?)
제 repo 에 push 했을 뿐인데 기존 PR 에 같이 딸려 가버리네요 ;;
리뷰 후 PR 하고 싶었는데..

**Comment by ChangJoo-Park** [comment]
Vue 공식 문서같은경우는 https://github.com/vuejs-kr/kr.vuejs.org 여기서 PR 해주시는게 보통이구요

다른 문서들은 다 vue 조직 안에 있어서 누군가 한국어 문서를 PR하시면 kazupon(일본 Vue 운영자?! 입니다)씨가 저에게 리뷰해달라고 해요
그다음에 제가 확인하고 완료되면 머지 요청합니다

**Comment by usolkim** [comment]
아 그러면 Vuex 경우에는 공식 repo 에 PR 하면 kazupon 님이 창주님께 리뷰 요청을 하는 방식이군요.
제가 한게 틀린 방식은 아니었네요~
답변 감사합니다^^
(이슈가 아닌 문의 였지만.. 답변을 받아서 클로즈 하겠습니다 ㅋㅋ)

**Comment by ChangJoo-Park** [comment]
Vuex PR올리신거 제대로 다시 확인했습니다 

요즘 다들 바쁜지 PR 확인을 잘 안하나봐요
