### ISSUE TITLE
창주님 PR 확인 부탁드립니다

### ISSUE THREAD

**Issue by usolkim** [vuejs-kr/vuejs-kr.github.io#117]
@ChangJoo-Park 
바쁘셔서 못 보시는 것 같아서 부득이하게 이곳에 글 남깁니다.
https://github.com/ChangJoo-Park/vue-router/pull/2
확인 후 머지 부탁드립니다.

**Comment by ChangJoo-Park** [comment]
PR 목록에 올려주신 내용이 왜 안나왔을까요 
놓쳐서 죄송합니다 ㅠㅠ

**Comment by usolkim** [comment]
그럴 수도 있죠 모^^
머지 감사합니다
