### ISSUE TITLE
슬랙 초대가 안됩니다 

### ISSUE THREAD

**Issue by AkiaCode** [vuejs-kr/vuejs-kr.github.io#123]
![image](https://user-images.githubusercontent.com/71239005/112414714-ddf58300-8d65-11eb-850a-13b9c60116cc.png)

**Comment by ChangJoo-Park** [comment]
@AkiaCode 
이메일을 남겨주시면 초대해드릴게요

**Comment by AkiaCode** [comment]
catry.me@gmail.com 입니다

**Comment by ChangJoo-Park** [comment]
초대 메일을 보내드렸어요 메일 확인부탁드려요

**Comment by AkiaCode** [comment]
확인했습니다 감사합니다
