### ISSUE TITLE
Plugin 사용법

### ISSUE THREAD

**Issue by kciter** [vuejs-kr/vuejs-kr.github.io#13]
직접 만든 모듈을 다른 프로젝트에서도 사용 할 수 있도록 Plugin 사용법과 예제에 대한 문서가 있으면 좋을 것 같습니다.

**Comment by ChangJoo-Park** [comment]
네 저도 요즘 이 생각하고있어요

**Comment by ChangJoo-Park** [comment]
@kciter 혹시 작성 해주실 의향이 있으신가요?

**Comment by ChangJoo-Park** [comment]
그 전에 어떤 종류의 플러그인이 있는지 정의하는게 우선이겠네요 의견주세요

**Comment by kciter** [comment]
우선은 공식 문서에 적혀있는
```js
MyPlugin.install = function (Vue, options) {
  // 1. 전역 메소드 또는 속성 추가
  Vue.myGlobalMethod = function () {
    // 필요한 로직 ...
  }
  // 2. 전역 에셋 추가
  Vue.directive('my-directive', {
    bind (el, binding, vnode, oldVnode) {
      // 필요한 로직 ...
    }
    ...
  })
  // 3. 컴포넌트 옵션 주입
  Vue.mixin({
    created: function () {
      // 필요한 로직 ...
    }
    ...
  })
  // 4. 인스턴스 메소드 추가
  Vue.prototype.$myMethod = function (options) {
    // 필요한 로직 ...
  }
}
```
이 정도에 실사용 예를 적어보면 어떨까 합니다 ㅎㅎ
후에 정리해서 PR 보내볼게요.

**Comment by ChangJoo-Park** [comment]
네 감사합니다.

[vue-plugin-boilerplate](https://github.com/kazupon/vue-plugin-boilerplate) 보시면 도움이 되실거에요

우선은 공식 문서 기준으로 하시는게 더 보기 편할 것 같구요. [ElementFe](http://element.eleme.io/#/en-US), [Quasar Framework](http://quasar-framework.org/) 처럼 UI 컴포넌트 만드는 부분도 문서가 필요하지 않을까 생각해요

**Comment by kciter** [comment]
감사합니다 :)

**Comment by ChangJoo-Park** [comment]
PR감사합니다.
