### ISSUE TITLE
유용한 코드 조각을 공유해요

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#14]
질문에 따라 흘러가버리는 코드조각을 저장해 놓으면 나중에 찾아보기 좋을 것 같습니다.

https://vuejs-kr.github.io/snippets/ 
이 위치에 모아두려고 공간은 만들었고 하나씩 추가해가면 도움이 될 것 같습니다
페이지에 보여질 형태는
**예제 이름 - 작성자 github 프로필 링크** 정도로 생각하고 있습니다.

# 참여방법
- 현재(2016년 1월)은 정해진 룰이 없습니다. 
- 공유하고 싶은 jsffidle, code-pen 등 링크는 이 곳에 올려주시면 추가하겠습니다. 제가 제목을 정하는데 어려움이 있습니다. 꼭 코드 조각에 대한 제목 달아주세요.
- 아니면 https://github.com/vuejs-kr/vuejs-kr.github.io/blob/master/snippets.md 이 파일을 수정하신 후 풀 리퀘스트를 남겨주세요

**Comment by ChangJoo-Park** [comment]
@kciter 님 https://jsfiddle.net/ezftu6kv/1/ 
이 링크 fiddle 로그인하시고 저장한 링크로 바꿔주시면 좋지 않을까 싶어요 원작자가 누군지 알 수 있는게 좋을 거 같아요 그리고 제목도 부탁드려요

**Comment by kciter** [comment]
@ChangJoo-Park 네 알겠습니다 :) 그러면 제가 링크 수정과 동시에 해당 이슈에 대한 PR 한 번 날려보겠습니다.

**Comment by ChangJoo-Park** [comment]
@kciter 제가 https://github.com/vuejs-kr/vuejs-kr.github.io/blob/master/snippets.md 여기에 양식 만들어서 하나 올려둘게요 비슷하게 가면 될 것 같아요 고쳐야 할 부분 있으면 알려주세요

**Comment by kciter** [comment]
감사합니다 :D

**Comment by ChangJoo-Park** [comment]
@kciter https://vuejs-kr.github.io/snippets/ 일단 가볍게 가는게 좋을 것 같아요

**Comment by ChangJoo-Park** [comment]
홈페이지에 이슈로 올 수 있는 링크를 추가해야할 필요가 있습니다.

**Comment by ChangJoo-Park** [comment]
조건에 따라 다르게 출력되는 레이아웃 
빈 Vue 인스턴스를 이벤트버스로 사용하기

추가하였습니다.

**Comment by judoaseeta** [comment]
http://codepen.io/Roychoi/pen/JWbgwG

 jsfiddle이 좀더 보기 쉬운거 같아서 jsfiddle로 하려고 했는데 디렉티브 구현이 안되어있는지 잘안되서 ,
codepen으로 구현하였습니다 .

커스텀 디렉티브 구현에 관한 짧은 예제입니다 .(https://kr.vuejs.org/v2/guide/custom-directive.html)
