### ISSUE TITLE
이벤트 버스를 이용한 컴포넌트 간 통신

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#22]
비어있는 Vue 인스턴스를 이벤트 버스로 사용하는 예제를 작성합니다.

**Comment by ChangJoo-Park** [comment]
https://jsfiddle.net/changjoo_park/d8qdz3za/

**Comment by ChangJoo-Park** [comment]
나중에 홈페이지에서 확인하시면 닫아주세요

**Comment by devjin0617** [comment]
네 감사합니다.

**Comment by ChangJoo-Park** [comment]
덕분에 이슈가 사라지는 마법을 보았습니다

**Comment by devjin0617** [comment]
그런가요? 제가 보기에는 이슈가 엄청 많은거 같아요 ㅇ_ㅇ...
홈페이지에 갱신된 것 확인하여 해당 이슈 닫도록 하겠습니다.
고생하셨습니다.

**Comment by ChangJoo-Park** [comment]
감사합니다
다 제가 열어놓고 처리안하는 게으름 탓이죠 뭐 ...
