### ISSUE TITLE
ko-fi 정책에 대하여..

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#31]
vuejs-kr 을 운영함에 있어 실험하는 내용 중 하나가 https://ko-fi.com 링크를 달아 놓은 것 입니다.
그런데 글을 올려놓고 해당 링크에서 ko-fi로 기부를 받는 경우 어떤 글에 대해 기부를 한 것인지 추적할 수 없습니다.
이 문제 때문에 ko-fi로 기부 받은 금액을 어떻게 사용할 지 생각해 봐야 할 것 같습니다.

현재 생각하는 것은 오프라인 모임 (있을지 모르겠습니다...) 이 있을 경우 돈이 드는 문제가 생길 때 가져다 쓰는 것이 가장 올바른 사용 용도라고 생각합니다. 현재는 기부해주시는 분이 적어서(@devjin0617 감사합니다) 문제가 되지 않지만 돈이 관련 되어 있어 미리 정해 놓고 홈페이지 문구도 수정하는 것이 맞을 것 같습니다.

**Comment by devjin0617** [comment]
기부금이 일정금액 모이면, 그때 피자먹을겸 오프라인을 진행해도 좋을 것 같습니다. (기술적으로 뭔가를 깊이 이야기하는 것보다 vuejs를 사용하면서 겪고 있는 고충들을 공유하는 관점에서)
해당 관련 내용의 대해서는 홈페이지 문구에도 포함하고 이슈 #15  `참여방법에 관한 설명서에`에도 작성되면 좋을 것 같습니다.

**Comment by ChangJoo-Park** [comment]
이슈 #15 를 잘 만들어야 겠네요 ㅎㅎ

**Comment by ChangJoo-Park** [comment]
**위 링크를 통해 후원을 받고 있습니다. 모든 후원금은 Vue.js 한국 커뮤니티 운영에 사용됩니다.**
위 문구로 수정하였습니다.

- 이전
https://github.com/vuejs-kr/vuejs-kr.github.io/commit/cfe0e7f026214a70b14f8f6fca3d773f3ac277bc

**위 링크를 통해 후원을 받고 있습니다. 모든 후원금은 글을 올려주신 분께 돌아갑니다.**
이 내용에 대해 관리가 힘들다고 판단되어 변경하였습니다.
