### ISSUE TITLE
`지시문`을 `디렉티브`로 번역하는 건에 대한 이슈

### ISSUE THREAD

**Issue by kciter** [vuejs-kr/vuejs-kr.github.io#41]
`지시문`을 `디렉티브`로 번역하는 것에 대해서 어떻게 생각하시나요?

**Comment by kciter** [comment]
치환 명령어를 사용하였습니다.
```
find ./ -iname '*.md' -exec sed -i '' -e 's/지시문은/디렉티브는/g' {} \;
find ./ -iname '*.md' -exec sed -i '' -e 's/지시문을/디렉티브를/g' {} \;
find ./ -iname '*.md' -exec sed -i '' -e 's/지시문이/디렉티브가/g' {} \;
find ./ -iname '*.md' -exec sed -i '' -e 's/지시문/디렉티브/g' {} \;
```

위 명령어를 사용했습니다.

**Comment by ChangJoo-Park** [comment]
엄청나네요 😱  
도와주셔서 감사합니다

**Comment by kciter** [comment]
헉 그런데 CI에 실패해버렸네요 ㅋㅋ

**Comment by ChangJoo-Park** [comment]
이거 원래 이래요

**Comment by kciter** [comment]
그렇군요 :D 감사합니다!

**Comment by kciter** [comment]
지금보니 `디렉티브과`로 되는 문제가 한 가지 있어서
`find ./ -iname '*.md' -exec sed -i '' -e 's/디렉티브과/디렉티브와/g' {} \;`
로 `디렉티브과`를 `디렉티브와` 처럼 보이도록 치환했습니다.

**Comment by ChangJoo-Park** [comment]
주말까지 다른 의견이 없는 경우 머지할 예정입니다. @kciter 님 감사합니다

**Comment by ChangJoo-Park** [comment]
https://github.com/vuejs-kr/kr.vuejs.org/pull/18

머지 후 이슈 닫습니다
