### ISSUE TITLE
README파일에 vue.js-kr.github.io 로컬에서 테스트방법 추가여부

### ISSUE THREAD

**Issue by devjin0617** [vuejs-kr/vuejs-kr.github.io#51]
`vue.js-kr.github.io`페이지에 PR요청시 로컬에서 테스트할 수 있도록 내용을 추가하는건 어떨까요?

예) ruby설치, jekyll설치, 서버실행 관련

**Comment by kciter** [comment]
#42 와 연관된 이슈일 것 같아요 :)

**Comment by devjin0617** [comment]
@kciter 넵! 연결해주셔서 감사합니다 :)

**Comment by ChangJoo-Park** [comment]
어떻게해야할지 고민해보겠습니다

**Comment by ChangJoo-Park** [comment]
@devjin0617 님께서 올려주신 내용이면 충분할 것 같습니다 
괜찮으시면 이슈 닫으셔도 될거같아요

**Comment by devjin0617** [comment]
넵 감사합니다. 해당이슈는 일단 닫도록 하겠습니다.
