### ISSUE TITLE
포스트 등록시 원본출처 작성여부

### ISSUE THREAD

**Issue by devjin0617** [vuejs-kr/vuejs-kr.github.io#54]
`vuejs-kr.github.io`홈페이지에 포스트 등록시 작성자 블로그와 함께 올리는 경우가 있을 것이라 생각됩니다. (혹시 저만그런가요?)

같이 올라오는 경우 @ChangJoo-Park 의견에 따르면 원본글의 출처를 상단에 표기하자라고 말씀하셨습니다.

저 개인적인 의견으로는 하단에 관련링크정도로 남겨도 될 것 같다라고 생각되는데, 해당 이슈보시는 분들의 의견들 취합후 어떻게 표기할지 논해보면 좋을 것 같습니다 : )

해당 이슈의 내용은 아래 링크 참고하시면 될 것 같습니다.

https://github.com/vuejs-kr/vuejs-kr.github.io/commit/963964fb8d77012845f2f1b5ae05be7935196372

**Comment by ChangJoo-Park** [comment]
저는 맨 처음에 알려주는게 좋은 것 같아요

**Comment by kciter** [comment]
저도 처음이 좋을 것 같습니다. :)

**Comment by ChangJoo-Park** [comment]
결정하시면 의견과 함께 이슈 닫아주세요

**Comment by devjin0617** [comment]
이슈 #15 로 연결시켰습니다.
해당 이슈 종료합니다.
