### ISSUE TITLE
Visual Studio Code를 이용한 Vue 앱 디버깅

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#59]
webpack 템플릿을 사용하는 vue-cli 기반 앱을 vscode를 이용하여 디버깅할 수 있습니다
템플릿의 스타일을 수정하는데는 무리가 있지만 vue의 스크립트 부분에 대한 디버깅은 잘 됩니다

**Comment by devjin0617** [comment]
항상 감사합니다

**Comment by ChangJoo-Park** [comment]
웹스톰에선 더 쉽게 할 수 있지 않을까 싶어요

**Comment by devjin0617** [comment]
잠깐 검색해보니, 웹디버깅 그냥 지원한다고 하네요 ㅇ_ㅇ
서버 실행할때 디버그 모드로 실행한 뒤에 그냥 브레이크 포인트.. 덜덜..

**Comment by ChangJoo-Park** [comment]
역시..ㅋㅋ
시간되시면 웹스톰에서 테스트 한번 부탁드려요

메소드마다 브레이크포인트 걸고 쓸 수 있으니까 개발할 때 편할거 같아요

**Comment by devjin0617** [comment]
네 알겠습니다 :) 감사합니다!

**Comment by LeoHeo** [comment]
음..이걸보니 `atom`은 없나? 라는 생각이 문득....아톰도 찾아보겠습니다.

**Comment by ChangJoo-Park** [comment]
@LeoHeo 부탁드릴게요 :)

아래 gist는 vscode용 설정입니다
https://gist.github.com/anonymous/dbff02b1409231708ba1d74e03615c93

**Comment by ChangJoo-Park** [comment]
뭔가 완벽하게 동작하지는 않네요 브레이크포인트가 다른데 걸린다던가 풀리는 경우도 있네요
