### ISSUE TITLE
Webstorm에서 Vue 앱 디버깅

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#60]
Webstorm Early Access Program 버전 다운로드
https://confluence.jetbrains.com/display/WI/WebStorm+EAP

크롬 확장 프로그램 설치
https://chrome.google.com/webstore/detail/jetbrains-ide-support/hmhgeddbohgjknpmjagkdomcpobmllji

Run/Debug configurations에서 Javascript Debug 추가
URL: http://localhost:8080/

최상위 프로젝트의 remote url을
webpack:///{{프로젝트 경로}} 로 설정

webpack.dev.conf.js 파일을 열고 devtool 내용을 아래로 바꿉니다
devtool: 'source-map',

Vue 파일에서 브레이크포인트를 걸고 디버그모드로 실행하면 됩니다

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park  Webstorm 에서 Vue 컴포넌트 디버깅 방법을 몰라 계속 console.log로 해결 했는데 감사합니다. :+1:

**Comment by ChangJoo-Park** [comment]
안녕하세요 ㅋㅋ
