### ISSUE TITLE
Vue로 만든 애플리케이션 소개 페이지 추가관련 논의요청

### ISSUE THREAD

**Issue by devjin0617** [vuejs-kr/vuejs-kr.github.io#64]
국내에서 Vue.js를 도입할지 말지 고민하는 회사들이 많은 것 같습니다.

한국어 사용자 공식 페이지에 Vue.js 사용/적용사례를 보여주고, 소개해주는 페이지가 있으면 좋을 것 같다고 생각하는데..

어떻게 생각하시나요?

**Comment by ChangJoo-Park** [comment]
공식페이지인가요 블로그인가요?

**Comment by devjin0617** [comment]
공식페이지에 추가하려면 해외 여러사람들의 동의가 필요할 것 같아서 무리일 것 같고,
`vuejs-kr.github.io` 여기 생각하고 있는데 어떠신가요?

> vuejs-kr.github.io 여기를 블로그라고 말씀하신거죠?

**Comment by ChangJoo-Park** [comment]
네 맞아요 ㅋㅋ
저는 괜찮은것 같아요 하게된다면 우선 사례를 모으는게 먼저일 것 같아요

**Comment by devjin0617** [comment]
감사합니다.
그래서 준비해보았습니다.

PR #66

**Comment by LeoHeo** [comment]
이거 상당히 좋은거 같습니다. 저도 오늘 vue좋다고(~약팔이~) 말하는데 돌아오는 대답이 `국내에서 많이 쓰나요?`
이 질문이여서 이거 생기면 링크 던져주면 되니깐 좋은거 같습니다.

**Comment by ChangJoo-Park** [comment]
> 국내에서 많이 쓰나요?

엄청 많이 들었어요 ㅋㅋ

**Comment by ChangJoo-Park** [comment]
https://github.com/vuejs-kr/vuejs-kr.github.io/pull/66  해당 PR과 함께 봐주세요

**Comment by devjin0617** [comment]
사례는 기존 올리고 있는 포스팅에 껴서 팔면 되지 않을까요 ㅇ_ㅇ? 호호호호

**Comment by ChangJoo-Park** [comment]
그런데 요즘 Vue 쓰는곳을 어떻게 알 수 있을까요 
쓰는 분들께서 참여 해서 올려주시는 방법 아니면 알 수 있는 방법이 있을까요

**Comment by Jungwoo-An** [comment]
음... 이건 좀 무식한 방법이긴 한데, 크롬 확장 프로그램 중에 wappalyzer 라는 것이 있습니다. 이걸 쓰면 접속한 웹사이트가 어떤 기술 스택을 사용하였는지 추론해서 보여줍니다!!

**Comment by ChangJoo-Park** [comment]
@o1o9814 엄청난게 있네요 
감사합니다 :)

**Comment by ChangJoo-Park** [comment]
테스트해봤는데 잘되네요 이제 일일히 들어가서 확인해봐야..........ㅋㅋ

**Comment by kciter** [comment]
그런데 직접올리는게 아니라면 허락을 받고 올려야하지 않을까요?

**Comment by ChangJoo-Park** [comment]
네 물론이죠

**Comment by devjin0617** [comment]
아마도 모임 또는 페이스북그룹을 통해 사례 계속 올려달라고 홍보하는 방법밖에 없을 것 같기는 합니다 😄

**Comment by ChangJoo-Park** [comment]
https://electron.atom.io/apps/ 
이렇게 가는 것도 생각해볼만한거 같아요

**Comment by Jungwoo-An** [comment]
추가된다면, 블로그인가요 가이드 페이지인가요?

**Comment by devjin0617** [comment]
@ChangJoo-Park 헤헤 그거보고 따라 만든게 PR #66 이였습니다 ㅎ_ㅎ;;;
@o1o9814 말씀하신 내용을 논의해보면 좋을 것 같아요 😄

**Comment by ChangJoo-Park** [comment]
역시 👍

**Comment by devjin0617** [comment]
해당 PR 완료되었으므로 이슈 종료합니다.
