### ISSUE TITLE
Vue.js와 Feathers.js에 관하여..

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#65]
[Feathers.js](http://feathersjs.com/)는 express + socket.io(혹은 primus 선택 가능) 기반의 백엔드 프레임워크 입니다
vue와 함께 간단하게 사용해보니 꽤 괜찮게 사용할 수 있을거라 생각이 드는데요
@LeoHeo 님 사용해보신 경험 공유 부탁드려요

vuex와 함께 사용해보았는데 꽤 괜찮게 응용해볼 거리가 많은 것 같아요

https://vimeo.com/206411600

컴포넌트에서 서비스로 백엔드로 전달하고 socket.io에서 발생한 이벤트로 vuex의 state를 갱신하는 작업을 해보았습니다 위 동영상은 간단히 찍어봤어요

**Comment by LeoHeo** [comment]
저는 왜 영상이 안나올까요??ㅠㅠ

Feathers.js에 대한 자세한 설명은 [introduction](https://docs.feathersjs.com/getting-started/introduction.html)에 잘 나와있다고 생각하고 일단 넘겨갑니다. ^^

일단 실무에서 써보지 않았고 `socket.io`를 제대로 활용한 무언가를 해보지 않았기 때문에

경험 공유에 있어서 좀 조심스럽지만 몇 글자 적어보겠습니다.

일단 제가 사용했던 총평은 `Rails`를 좋아하시는 분들이면 참 좋아하겠구나 라는걸 그 당시 느꼈습니다.

이렇게 생각한 이유는 `장점` 부분때문입니다. 

## 장점
-  CLI 명령어 한줄로 손쉽게 API서버를 구축(`middleware`, `service`, `hook`)이 가능합니다.
- `service`를 하나 만들면 `GET`, `POST`, `DELETE`, `PUT`등이 자동 생성되어서 바로 `Postman`으로 테스트를 할 수가 있어서 좋았습니다.
- `hook`은 작업을 시작하기 `전`과 `후`에 할 작업을 추가 할 수 있었는데 `generate`된 파일 소스를 까보면 직관적으로 되있었습니다. (제 생각엔)
- [공식 organization](https://github.com/feathersjs)에서 정말 다양하게 지원되는거 엄청 많습니다.
- 특히나 [authentication](https://github.com/feathersjs/feathers-authentication) 관련 작업은 정말 엄청 편했습니다.
- [공식 슬랙](http://slack.feathersjs.com/)에서 누군가가 질문을 하면 바로바로 답변을 친절하게 잘해 주십니다.

## 단점
- `Customizing`이 힘들게 느껴졌습니다. 간단한 그냥 `CRUD`만 할꺼면 딱히 문제가 될건 없는데 이걸 좀 뜯어고치는게 힘들다고 느꼈습니다.

## 어려웠던 점
- 고수가 하기에는 어떨지 모르겠지만 초보가 만약 뜯어고치고 싶다 그러면 좀 많이 힘들더군요.........특히나 `Promise`에 대한 이해도가 낮은 상태라서 더 힘들었던거 같습니다.

두서 없이 작성하기는 했는데...어떠실지 모르겠네요ㅎㅎ

**Comment by ChangJoo-Park** [comment]
답변 너무 잘 해주셔서 놀랬어요 그냥 궁금했던거라서.. 유튜브에서 @LeoHeo 님 댓글을 봐서 질문드렸어요
아.. 제가 레일즈를 좋아해서 좋았던거 같네요 ㅋㅋ 정곡을 찔렸네요
커스터마이징은 저도 아직 잘 안해봐서 잘 모르겠어요 초반이라 기본적으로 제공하는 것들을 따라가는 것만 해도 할게 많네요

그냥 구성이 잘 되어있는 express쓴다 생각하고 쓰고 있어요 조금 더 해볼게요

vimeo에 올렸는데 이상하게 안나오네요 

![Imgur](http://i.imgur.com/9VTCfxQ.gif)
