### ISSUE TITLE
미트업 준비

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#67]
이번달에 한번 모임이 있었으면 하는데 관련해서 의견 부탁드려요

**Comment by kciter** [comment]
저는 찬성합니다. :)
단순히 친목을 위한 모임이 아니라면 위치와 주제가 문제일 것 같아요.

**Comment by ChangJoo-Park** [comment]
저는 친목은 가족/친구들과 하는게 좋다고 생각해요
일부러 시간내서 오시는데 뭐 하나라도 얻어가는게 있어야 하지 않을까 싶어요

**Comment by devjin0617** [comment]
미트업가면 피자 있나요?

**Comment by ChangJoo-Park** [comment]
ㅠㅠ

**Comment by Jungwoo-An** [comment]
선협님이 발표도 하시는 건가요?

**Comment by ChangJoo-Park** [comment]
그렇다고 하시던데요 
근거는 없습니다

**Comment by devjin0617** [comment]
이슈가 잘 해결되어 종료합니다 😄
