### ISSUE TITLE
Vue 관련 프로젝트 소개하는 페이지

### ISSUE THREAD

**Issue by Jungwoo-An** [vuejs-kr/vuejs-kr.github.io#71]
Vue 한국어 모임 깃허브 페이지에 관련 프로젝트를 소개하는 메뉴를 추가했으면 좋겠습니다. 이것은 Vue 의 생태계를 한 눈에 볼 수 있고, 타 프레임워크 숙련자들이 고민 없이 Vue를 시작할 수 있게 만들어줍니다. 또, 간략한 부연 설명을 붙이게 되면 검색을 통한 시간 낭비를 줄일 수 있을 것으로 보입니다.

현재 깃허브 페이지에는 한국어 번역 프로젝트라는 메뉴가 존재하는데, 이 메뉴에 통합하는 건 어떨까요?

**Comment by ChangJoo-Park** [comment]
[aweseome-vue](github.com/vuejs/awesome-vue)가 있지 않나요?

**Comment by Jungwoo-An** [comment]
시작할 수 있습니다 -> 시작할 수 있게 만들어줍니다. 이슈에는 수정 버튼이 존재하지 않네요. :joy:

**Comment by ChangJoo-Park** [comment]
제가 수정했어요
수정 버튼이 없나요 처음알았어요

**Comment by Jungwoo-An** [comment]
Awesome-@@ 도 좋지만, 해당 자료는 부연 설명이 없고, 한국어 자료가 있으면 초심자에게 더 친근하게 다가올 수 있을 것 같습니다.

**Comment by Jungwoo-An** [comment]
제가 모바일이라 해당 버튼이 안 보이는 것 같습니다.

**Comment by ChangJoo-Park** [comment]
의견 부탁드려요

**Comment by devjin0617** [comment]
vue관련 프로젝트들은 국내보다는 해외에 자료들이 많아서 해당 자료들을 설명하고 나열하다보면 중복적인 일이 되지는 않을까요?

**Comment by Jungwoo-An** [comment]
중복 문제는 생각해보지 않았네요.

**Comment by Jungwoo-An** [comment]
음.. 생각보다 크게 문제가 될 것 같지는 않습니다. 어차피 문서에 추가될 때엔 컨트리뷰터 분들이 리뷰를 하실 테니...??????

**Comment by ChangJoo-Park** [comment]
위에 적어주신 관련 프로젝트 설명이 어떤 것을 말씀하시는지 알 수 있을까요?
플러그인 혹은 라이브러리면 사용기를 포스트로 작성해도 충분할 것 같아서요

**Comment by devjin0617** [comment]
아, 중복이라는 이야기는 해외에 있는 내용을 가져오는 수준이 되지않을까라는 의견입니다 (awesome-vue를 번역하는 느낌이랄까..)

음 개인적인 의견입니다.

**Comment by Jungwoo-An** [comment]
현재 comfuture 님이 진행하고 계신 semantic-ui-vue 같은 경우 'semantic-ui css 를 vue로 래핑한 프로젝트 입니다유사한 타 프로젝트와는 다르게 @@까지 진행되었으며, 국내에 계신 @@님께서 @@했습니다.' 와 같이 설명을 붙일 수 있겠습니다. 단순히 보여주는 목적도 있지만, 해외에 비해 프로젝트를 알리기 쉽지 않은 국내 프로젝트를 살리는 목적도 있습니다.

**Comment by Jungwoo-An** [comment]
@devjin0617
무작정 추가만 하는 것이라면 그럴 수도 있겠지만, 컨트리뷰터 분들이 계신다면 빈약한 자료는 추가되기 힘들 것 같습니다.

**Comment by ChangJoo-Park** [comment]
@o1o9814 공감하는 부분이에요
문제는 관리/유지가 될까? 싶어서요

**Comment by Jungwoo-An** [comment]
@ChangJoo-Park 맞는 말씀이네요.
관리와 유지에 관해서는 좀 더 생각해봐야 할 것 같아요.

**Comment by ChangJoo-Park** [comment]
마구 기능이나 내용을 못늘리는게 사람은 적은데 할일이 너무 많아질까 싶어서요
@o1o9814 의견 주신 내용은 필요하겠지만 누가 맡아서하지? 라는 생각부터 들었어요

**Comment by Jungwoo-An** [comment]
@ChangJoo-Park 그 정도까진 생각해보지 못했던 것 같아요. 의견 주셔서 감사합니다.

**Comment by ChangJoo-Park** [comment]
나중에 말씀해주신 내용이 필요하면 다시 열겠습니다
