### ISSUE TITLE
index.html 리스트 부분 레이아웃 관련

### ISSUE THREAD

**Issue by Jungwoo-An** [vuejs-kr/vuejs-kr.github.io#72]
현재 리스트 부분의 레이아웃 배치가

#### 부연 설명

형식으로 되어있습니다. 이 부분을 아래처럼 변경하면, 좀 더 깔끔할 것 같다는 생각이 듭니다.

**Comment by Jungwoo-An** [comment]
![미리보기](http://imgdb.kr/blAm.dn)

한 번 수정해봤습니다!

**Comment by ChangJoo-Park** [comment]
더 보기 좋아보이네요 PR 해주실 수 있나요?

**Comment by Jungwoo-An** [comment]
#73 PR 올렸습니다. 이 이슈는 제가 닫도록 하겠습니다!
