### ISSUE TITLE
[버그] 각 페이지 hover 효과가 나타납니다. (버그 GIF첨부)

### ISSUE THREAD

**Issue by devjin0617** [vuejs-kr/vuejs-kr.github.io#74]
제가 고칠 수도 있겠지만 혹시 고칠시간이 없을 수도 있으므로 일단 기록용으로 이슈 남겨놓습니다.

![vuejs_kr_hover](https://cloud.githubusercontent.com/assets/5671786/23830883/27368066-0758-11e7-80d5-cae525d20656.gif)

**Comment by Jungwoo-An** [comment]
앗, 메인 페이지에서 사용자 반응을 추가해보고 싶어서 넣었던 건데, 다른 페이지에서도 같은 클래스 네임을 사용하고 있었나 보네요.

**Comment by devjin0617** [comment]
@o1o9814 아! 그렇군요! 시간되실 때, 고쳐주세요 : ) 시간 안되시면 제가 바꿔놓을께요 😄

**Comment by Jungwoo-An** [comment]
@devjin0617 해결해서 pr 넣었습니다~~. 알려주셔서 감사합니다.

**Comment by devjin0617** [comment]
이슈종료하겠습니다
