### ISSUE TITLE
Meetup 포스트 404 에러

### ISSUE THREAD

**Issue by myungseokang** [vuejs-kr/vuejs-kr.github.io#83]
https://vuejs-kr.github.io/
위의 메인 페이지에서

![2017-04-10 9 08 51](https://cloud.githubusercontent.com/assets/12431127/24842096/630a6202-1dcd-11e7-97ba-e60144803b68.png)

위의 포스트를 누르고 들어가면 404 에러가 뜨는 현상이 있습니다.

https://vuejs-kr.github.io/meetup/2017/03/29/meet-up-1/

저 링크를 클릭했을 경우 위의 링크로 가게 되는데 이 페이지를 jekyll 쪽에서 인식을 못하는 문제이지 않을까 싶습니다.
(확인해보니 `meetup/_posts` 라는 폴더가 있더라구요.)

**Comment by ChangJoo-Park** [comment]
감사합니다
@kciter 확인 부탁드려요

**Comment by kciter** [comment]
https://github.com/vuejs-kr/meetup
이 저장소를 만들어서 그렇군요ㅠㅠ
네이밍을 변경하는 방법으로 가야할 것 같습니다.

**Comment by devjin0617** [comment]
바쁘신 것 같아 일반 포스트로 변경/이동 하였습니다 (카테고리도 임시로 제외)
이슈 닫을께용 😄

**Comment by kciter** [comment]
감사합니다 :D
