### ISSUE TITLE
$nextTick 사용 방법

### ISSUE THREAD

**Issue by ChangJoo-Park** [vuejs-kr/vuejs-kr.github.io#9]

**Comment by ChangJoo-Park** [comment]
https://jsfiddle.net/devjin0617/pgscu4q3/

@devjin0617 님께서 기여해주셨습니다

**Comment by ChangJoo-Park** [comment]
@devjin0617 시간 되시면 부탁드려요 안되시면 저에게 assign 해주세요

**Comment by devjin0617** [comment]
@ChangJoo-Park 포스트 말씀하시는거죠?

**Comment by devjin0617** [comment]
`jsfiddle`, `post` 작성완료되어 해당이슈 닫도록 하겠습니다. 이후 부족한 내용있으면 이슈진행 부탁드리겠습니다.
감사합니다.
